#! /bin/bash

if [ "$dpenviron" = "" ]; then
  echo Please export dpenviron
  exit 1
fi
echo dpenviron $dpenviron

if [ "$3" = "" ]; then
  echo Usage:
  echo $0 dpdomain obj-filespec deployment-policy
  echo where obj-filespec can be an xcfg or an export zip
  exit 1
fi

DCM_HOME=~/dcm
DPCONFIG=~/.dpbuild
DPBUILD=$(dirname $(readlink -f $0))
DPBUILDTMP=$(mktemp -d)

# $1 - domain
# $2 - obj to deploy
# $3 - deployment policy object name

dpdomain=$1
# dcm needs full path
objfile=$(readlink -f $2)
dpo=$3

ant -f $DCM_HOME/deploy.ant.xml \
 -Ddcm.dir=$DCM_HOME \
 -Dwork.dir=$DPBUILDTMP \
 -propertyfile $DPCONFIG/$dpenviron.properties \
 -Ddomain=$dpdomain \
 -Dimport.file=${objfile} \
 -Ddeployment.policy.object=$dpo \
 import-dpo

if [ $? -ne 0 ]; then
  exit 1
fi

rm -rf $DPBUILDTMP
