#! /bin/bash
echo "*** Enter dcm-check-access"
if [ "$dpenviron" = "" ]; then
  echo Please export dpenviron
  exit 1
fi
echo dpenviron $dpenviron

DCM_HOME=~/dcm
DPCONFIG=~/.dpbuild
DPBUILD=$(dirname $(readlink -f $0))
DPBUILDTMP=$(mktemp -d)

ant -f $DCM_HOME/deploy.ant.xml \
 -Ddcm.dir=$DCM_HOME \
 -Dwork.dir=$DPBUILDTMP \
 -propertyfile $DPCONFIG/$dpenviron.properties \
 -Ddomain=default \
 check-access

if [ $? -ne 0 ]; then
  echo "ant check-access call returned non-zero: " $?
  exit 1
fi

rm -rf $DPBUILDTMP
echo "*** Exit dcm-check-access"