#! /bin/bash

# this file gets sourced into dputils scripts

# we expect the user to have exported dpenviron, which defines
#   the DataPower box

if [ "$dpenviron" = "" ]; then
  >&2 echo Please export dpenviron
  exit 1
fi
>&2 echo dpenviron $dpenviron

# the dpConfig folder will have properties files
# we're trying to stay compatible with DCM
# default to ~/.dputils if not set
: ${dpConfig:=~/.dputils}
>&2 echo dpConfig $dpConfig

# default soma port, can be overriden in properties
port=5550

source $dpConfig/$dpenviron.properties

>&2 echo SOMA host $host
>&2 echo SOMA port $port

# create the soma request
# we will get the domain, and the contents to be put into dp:request
function somaReq() {
  dpdomain=$1
  dpreq=$2

  tmpfile=$(mktemp)

  cat <<EOF1 >$tmpfile
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <dp:request xmlns:dp="http://www.datapower.com/schemas/management"
      domain="${dpdomain}">
EOF1
  echo "$dpreq" >>$tmpfile
  cat <<EOF2 >>$tmpfile
    </dp:request>
  </env:Body>
</env:Envelope>
EOF2
  >&2 cat $tmpfile
  curl -k -u $uid:$pwd -d@$tmpfile https://$host:$port/service/mgmt/current
  rm $tmpfile
}
