#! /bin/bash

dpHome=$(dirname $(readlink -f $0))
source $dpHome/dp-include

if [ "$2" = "" ]; then
  >&2 echo Arguments missing
  >&2 echo Usage: $0 domain location
  >&2 echo location local: cert: etc. \(Colon required\)
  exit 1
fi

dpdomain=$1
dplocation=$2

dprequest=$(cat <<EOF0
  <dp:get-filestore location="${dplocation}"/>
EOF0
)
somaReq $dpdomain "$dprequest"
