#! /bin/bash

dpHome=$(dirname $(readlink -f $0))
source $dpHome/dp-include

if [ "$3" = "" ]; then
  >&2 echo Usage: $0 domain fspecxcfg dpolicy
  exit 1
fi

dpdomain=$1
fspecxcfg=$2
dpo=$3

dprequest=$(cat <<EOF0
  <dp:do-import
    source-type="XML"
    dry-run="false"
    overwrite-files="false"
    overwrite-objects="true"
    rewrite-local-ip="false"
    deployment-policy="${dpo}">
    <dp:input-file>
EOF0
base64 ${fspecxcfg}
cat <<EOF1
    </dp:input-file>
  </dp:do-import>
EOF1
)
somaReq $dpdomain "$dprequest"
