#! /bin/bash

dpHome=$(dirname $(readlink -f $0))
source $dpHome/dp-include

if [ "$1" = "" ]; then
  >&2 echo No domain specified
  >&2 echo Usage: $0 domain
  exit 1
fi

dpdomain=$1

dprequest=$(cat <<EOF0
  <dp:get-config class="DomainSettings"/>
EOF0
)
somaReq $dpdomain "$dprequest"
